trigger:
  branches:
    include:
      - main
  paths:
    include:
      - dev/**
      - qa/**
      - PreProd/**
      - Prod/**

variables:
  subscription_id   : "74f18b4b-73a2-49ee-a8b5-9e6f8c8ec835"
  tenant_id         : "445535a9-31f3-4c74-a04b-348d3e339d24"
  client_id         : "39de24ed-e4cc-4d52-87f0-563963da45be"
  client_secret     : "8f8QXIKQ_iaGwEtDDsQkP1e3GT9Kx112BP2ahw"

stages:
  - stage: Deployment
    jobs:
      - job: Deployment
        displayName: 'Azure Deployment'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              cd dev
              terraform init
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Deployed'
