trigger:
  branches:
    include:
      - main
  paths:
    include:
      - dev/**
      - qa/**
      - PreProd/**
      - Prod/**

variables:
  subscription_id   : "74f18b4b-73a2-49ee-a8b5-9e6f8c8ec835"
  tenant_id         : "8d8d4417-60ec-4a46-ae73-5710d3caca54"
  client_id         : "12703015-a0a4-4368-916e-0ae47e8d2dc0"
  client_secret     : "CDg8Q~Hx6Gu7mM1E3-jN~u3O-1~jPjv5SyrwQb4G"

stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        displayName: 'Deploy Infrastructure to Azure'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              cd dev
              terraform init
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Deploying'
